version: '3.8'

services:
  landscap:
    image: landscape:x86_64
    container_name: land_rt
    privileged: true
    pull_policy: if_not_present
    environment:
      LAND_SCAPE_EBPF_MAP_SPACE: docker
    volumes:
      - ./.landscape-router:/root/.landscape-router
      - /sys/fs/bpf/:/sys/fs/bpf/
    networks:
      - out
      - br

  firefox:
    image: jlesage/firefox
    environment:
      LANG: zh_CN.UTF-8
      ENABLE_CJK_FONT: 1
    ports:
      - "5800:5800"
    networks:
      - br

networks:
  out:
    driver: bridge
  br:
    driver: bridge
