version: '3.8'

services:
  landscap:
    image: landscape:x86_64
    container_name: land_rt
    privileged: true
    pull_policy: if_not_present
    volumes:
      - ./.landscape-router:/root/.landscape-router
      # - /sys/fs/bpf:/sys/fs/bpf TODO: diff name mapping
    networks:
      - out
      - br

  firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
    networks:
      - br

networks:
  out:
    driver: bridge
  br:
    name: br
    driver: bridge
