when:
  - event: [push, manual]
  - path: 'docs/*'
labels:
  name: jp35

steps:
- name: build
  image: node:18.20.7-alpine3.21
  commands:
  - cd docs
  - ls -la
  - yarn install --cache-folder /yarn
  - yarn run docs:build
  - ls -la .vitepress/dist
  - mv .vitepress/dist/* /landscape/
  - ls -la /landscape
  volumes:
  - /d/landscape/html:/landscape
  - /d/agent_cache/yarn:/yarn
